[WIP] Enable BGP validate  collection contents
redhat-cop/network.bgp pull request #1
Opened 2022-06-06 17:24 UTC by rohitthakur2590

Signed-off-by: Rohit Thakur <rohitthakur2590@outlook.com>

2022-06-17 07:57 UTC, NilashishC commented on roles/bgp_health/tasks/main.yml
> +      name: ansible.netcommon.pyats
The `show bgp summary` isn't the most appropriate command in all cases and is deprecated for IOS-XE.

We should (a) find the correct command(s) for all platforms and map them in vars, (b) evaluate which parsing engine is best suited for converting the output from those commands to structured data.
In quite a few cases, using native parsing engine and our own hand written parsers turn out to be more precise.

2022-06-17 07:59 UTC, NilashishC commented on roles/bgp_health/includes/health_checks/junos.yaml
> +- set_fact:
We don't seem to be evaluating any op state data here.

2022-06-17 07:59 UTC, NilashishC commented on roles/bgp_health/includes/write_to_file.yaml
> +- name: Write each resource to a file
What is the benefit of persisting operational state data to a file?

2022-06-20 04:28 UTC, rohitthakur2590 commented on roles/bgp_health/includes/health_checks/junos.yaml
> +- set_fact:
At moment we are extracting limited  information as it is still in progress.
There will be  a generic model with more attributes for example all_neighbours_up/down/active, etc

2022-06-20 04:28 UTC, rohitthakur2590 commented on roles/bgp_health/includes/write_to_file.yaml
> +- name: Write each resource to a file
nothing as such , it is to be removed/may be put as optional.

2022-06-20 04:28 UTC, rohitthakur2590 commented on roles/bgp_health/tasks/main.yml
> +      name: ansible.netcommon.pyats
yes you are absolutly right, This work is already in progress and will be updated shortly.

2022-10-17 20:22 UTC, trishnaguha requested changes

2022-10-17 20:22 UTC, trishnaguha commented on README.md
> +  - name: BGP Manager
We should specify what this task is actually doing. One liner on health check.

2022-10-17 20:22 UTC, trishnaguha commented on README.md
> +  - name: BGP Manager
We should specify what this task is actually doing.

2022-10-17 20:22 UTC, trishnaguha commented on README.md
> +  - name: BGP Manager
We should specify what this task is actually doing.

2022-10-17 20:22 UTC, trishnaguha commented on README.md
> +  - name: BGP Manager
We should specify what this task is actually doing.

2022-10-25 15:57 UTC, merged