Restructuring work for BGP
redhat-cop/network.bgp pull request #56
Opened 2024-11-28 05:15 UTC by roverflow

Restructuring work for BGP

2024-11-28 08:40 UTC, rohitthakur2590 requested changes

2024-11-28 08:40 UTC, rohitthakur2590 commented on roles/deploy/README.md
> +network.bgp.deploy
Can we add more details here

2024-11-28 08:40 UTC, rohitthakur2590 commented on roles/detect/README.md
> +network.bgp.detect
Can we add more details here

2024-11-28 08:40 UTC, rohitthakur2590 commented on roles/gather/README.md
> +network.bgp.gather
Can we add more details here

2024-11-28 08:40 UTC, rohitthakur2590 commented on roles/persist/README.md
> +network.bgp.persist
Can we add more details here

2024-11-28 08:40 UTC, rohitthakur2590 commented on roles/remediate/README.md
> +network.bgp.remediate
Can we add more details here

2024-11-28 08:40 UTC, rohitthakur2590 commented on roles/remediate/tasks/main.yaml
> +  ansible.builtin.include_tasks: resources.yaml
why do we still need this directory ?

2024-12-03 10:30 UTC, rohitthakur2590 requested changes

2024-12-03 10:30 UTC, rohitthakur2590 commented on roles/configure/README.md
> +================
This is where we need to provide documentation for description , examples and variables  for the role

2024-12-03 10:30 UTC, rohitthakur2590 commented on roles/configure/defaults/main.yml
> +---
we can get rid of directories which are empty , or has empty files

2024-12-03 10:30 UTC, rohitthakur2590 commented on roles/configure/handlers/main.yml
> +---
If not needed lets remove handlers directory

2024-12-03 10:30 UTC, rohitthakur2590 commented on roles/configure/tasks/main.yaml
> +    operation: "configure"
so in main.yaml can we include validation task and then may be including task which points to configure.yaml file with this task
for example : https://github.com/rohitthakur2590/network.backup/blob/main/roles/backup/tasks/main.yaml

2024-12-03 10:30 UTC, rohitthakur2590 commented on roles/configure/vars/main.yml
> +# vars file for bgp_configure
if not needed get rid of directory

2024-12-03 10:30 UTC, rohitthakur2590 commented on roles/deploy/tasks/main.yaml
> -  ansible.builtin.include_tasks: includes/resources.yaml
same as for the configure role

2024-12-03 10:30 UTC, rohitthakur2590 commented on roles/health_checks/README.md
> +================
same comment as for configure role documentation

2024-12-03 10:39 UTC, rohitthakur2590 requested changes
I believe the var names we have used in the tasks , should be appended with role name.

2024-12-04 16:14 UTC, rohitthakur2590 requested changes

2024-12-04 16:14 UTC, rohitthakur2590 commented on roles/deploy/README.md
> +  hosts: rtr1
lets have hosts: all

2024-12-04 16:14 UTC, rohitthakur2590 commented on roles/health_checks/tasks/main.yaml
> +  ansible.builtin.include_tasks: "{{ operation.name }}.yaml"
why we need operation ? is it relevant anymore ?

2024-12-05 04:12 UTC, roverflow commented on roles/health_checks/tasks/main.yaml
> +  ansible.builtin.include_tasks: "{{ operation.name }}.yaml"
Removed it and invoked the task directly

2024-12-05 11:30 UTC, rohitthakur2590 approved these changes
Minor Comment , otherwise LGTM!

2024-12-05 11:30 UTC, rohitthakur2590 commented on roles/health_checks/README.md
> +================
@roverflow  Can we have this Documentation in same format as we have other roles

2024-12-05 12:29 UTC, merged